name: DisableLoreCraft
main: online.inferniaserver.mc.main
version: 1.2-Beta
commands:
 disablelorecraft:
  description: /<command> [reload]
  permission: disablelorecraft.admin
permissions:
 disablelorecraft.*:
  default: op 